import "@/styles/globals.css"

import { Toaster } from "@energizeai/ui/sonner"
import { TooltipProvider } from "@energizeai/ui/tooltip"
import { cn } from "@energizeai/ui/utils"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata } from "next"

import { ThemeProvider } from "@/components/theme/theme-provider"
import { ThemeToggle } from "@/components/theme/theme-toggle"

import SideNav from "./_components/side-nav"
import TopNav from "./_components/top-nav"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased overflow-y-scroll overflow-x-hidden",
          `${GeistSans.variable} ${GeistMono.variable}`
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeToggle shortcutOnly />
          <TooltipProvider delayDuration={0}>
            <div className="flex flex-col gap-4">
              <TopNav />
              <div className="flex flex-row gap-10 mx-auto px-4 max-w-screen-xl w-full pt-2 pb-4">
                <SideNav />
                <div className="flex-1 overflow-hidden max-w-full">
                  {children}
                </div>
              </div>
            </div>
          </TooltipProvider>
          <Toaster duration={3000} />
        </ThemeProvider>
      </body>
    </html>
  )
}
